### ISSUE TITLE
Encrypted Backup Issues

### ISSUE THREAD

**Issue by kayaelle** [digitalcredentials/learner-credential-wallet#395] opened 2023-03-20 19:01 UTC
From Pivotal list

Labels: none

status: unstarted

created Dec 15, 2022

by Brandon

Description:

**Comment by bmuramatsu** [comment] 2023-03-21 12:36
Duplicate of https://github.com/digitalcredentials/learner-credential-wallet/issues/302

**Comment by bmuramatsu** [comment] 2023-03-21 12:37
Duplicate of https://github.com/digitalcredentials/learner-credential-wallet/issues/394

**Closed by bmuramatsu** 2023-03-21 12:37 UTC
Labels: import from pivotal
