### ISSUE TITLE
Credential Display varies between Home and Credential Preview both iOS and Android

### ISSUE THREAD

**Issue by bmuramatsu** [digitalcredentials/learner-credential-wallet#478] opened 2023-08-10 19:48 UTC
This is for the test credential Dmitri just created for BCSI, and [one generated by Kayode](https://github.com/digitalcredentials/docs/tree/add-example-credentials/example-credentials/criteria-markdown-combo).

In both iOS and Android, v2.0.9-build 65 the text for the nominal badge name / credential name is different on the Home Screen and on the credential preview.

It looks like different fields are being rendered in each location.

**Credential Preview = DCC Test Credential **
<img src="https://github.com/digitalcredentials/learner-credential-wallet/assets/752326/d2e0a9f3-baab-45f4-9132-85d97a474205" width=30%>

**Home = Badge**
<img src="https://github.com/digitalcredentials/learner-credential-wallet/assets/752326/2986c9a3-faee-446f-9603-81ec3e9a4236" width=30%>

(This also occurs for the test credential Dmitri made on 8/10 with different value
[SharedCredential.txt.zip](https://github.com/digitalcredentials/learner-credential-wallet/files/12316738/SharedCredential.txt.zip)
s, you can see the wrong label reads as "Documentation and SOP" when it should be "Evaluator" in the Home screenshot.

Attached is the json for the DCC Test Credential.

To reproduce add the attached credential and view the name on the Home screen and Credential Preview screen.

**Comment by jmcioffi4** [comment] 2023-08-11 17:25
I am a little confused still, so do you mind clarifying which font specifically they need to be (and any other helpful information) and we can look into it on Monday?

**Comment by jmcioffi4** [comment] 2023-08-11 17:29
ignore previously deleted commented - will ask any questions we have on Monday instead when we have more time to look into it :)

**Comment by kayaelle** [comment] 2023-08-14 01:16
@bmuramatsu & @dmitrizagidulin - the reason this is happening is because the credentialDisplay is using AchievementCredential.name. The acceptance and list page are using AchievementSubject.Achievement.name. For the BCSI credential, the AchievementCredential.name in the spreadsheet is "Certified Evaluator" and AchievementSubject.Achievement.name doesn't have a value in the spreadsheet.

Two questions:

1. What should the AchievementCredential.name & AchievementSubject.Achievement.name - keep in mind that AchievementCredential.name is intended to be unique per credentials and AchievementSubject.Achievement.name is the name that would typically get repeated across badges like in a badge class. These don't need to be different. In OBv2, there was only one name field But, we should consider how the LCW handles this. 
2. Should the name be "Certified Evaluator" vs "Certified Evaluator"?

Atomic Jolt team - please hold on this until I give the go-ahaead. Moving this to backlog until then. Thanks!

**Comment by bmuramatsu** [comment] 2023-08-14 14:47
I think there are additional things going on in addition to what Kerri mentions. I address @kayaelle's points in 1 and 2 below.

(I should note I'm using the credential Dmitri shared on Thursday in slack, and v2.0.10-Build 65. Light Mode.)

1. What's in the Google doc for the pre-test and test.
2. What's in the data that Dmitri used to create the credential we've been viewing.
3. What LCW is displaying on the Credential Preview Screen.
4. What LCW is displaying on the Home Screen.
5. Note that the same display of data is happening in the credentials that Kayode created as test samples.

**1. What's in the [Google sheet](https://docs.google.com/spreadsheets/d/1hZ9z9jTFToAN4Lgvpm1r8B8S_6beU4Bsft-6cA3HvzM/edit#gid=0) for the pre-test and test.**

For BCSI there are not credential names that are unique by recipient. Then, based on the definitions provided by Kerri, column H in the spreadsheet should be labeled, `achievementSubject.Achievement.name` as it is "name that would typically get repeated across badges like in a badge class". I've updated that spreadsheet accordingly.

**Note**: I also updated the [Google sheet](https://docs.google.com/spreadsheets/d/1hZ9z9jTFToAN4Lgvpm1r8B8S_6beU4Bsft-6cA3HvzM/edit#gid=0) with a non-badgr hosted `Achievement.image.id`. I forgot to update the data after Angela provided an alternate location.

**2. What's in the data that Dmitri used to create the credential we've been viewing.**
From [Slack](https://mitodl.slack.com/archives/C03US24E6E9/p1691695498371669), Dmitri shared a link to a sample credential: `dccrequest://request?issuer=https%3A%2F%2Fissuer.example.com&vc_request_url=https://verify.dcconsortium.org/request/credential&challenge=ke12345678-0001&auth_type=bearer`

I wasn't as concerned about the data when I submitted the issue. This issue focused on what I saw when displaying the credential, vs. the info used to generate the credential. Both are needed, but I didn't dig into the info itself.

The _correct_ information does need to get added for the BCSI test, and that **_info is in the [Google sheet](https://github.com/digitalcredentials/docs/tree/add-example-credentials/example-credentials)_**, but I figured we could take care of that next pass.

I think that some of the issues of the info used to create the credential and what's displayed are interlinked.

Things to check on the next review are the [text in columns](https://docs.google.com/spreadsheets/d/1hZ9z9jTFToAN4Lgvpm1r8B8S_6beU4Bsft-6cA3HvzM/edit#gid=0) G, H, I, J, L, M, O, P, Q showing up as intended?

For the purposes of development Line 2 for "Test Evaluator" or Line 3 for "Angela Consani" could be used. Line 2 has an expiration date, Line 3 does not (as Angela's credential does not expire).

**3. What LCW is displaying on the Credential Preview Screen for the name.**
Looking at the credential Dmitri created and as shown in the screenshot and viewing the JSON of the credential, the text "Evaluator" seems to come from `vc.name`. (It's the only entry that "Evaluator" shows up.)

I think that's correct because that's where we'd put `vc.name`. Perhaps in the code `achievementSubject.Achievement.name` would also be displayed there if it existed in the JSON/info used to create the credential. This, I think is a related issue that doesn't need to be resolved now: What happens if there is conflicting data between VC and OBv3 fields, and what do we support?

And it seems that if `achievementCredential.name` existed then we'd probably want to display that instead of `achievementSubject.Achievement.name` per Kerri's description. Or as a related issue but one that does not need to be resolved now: Do we put the same information into both fields when we issue the credential for downstream compatibility if there is no "name that is unique per credential"?

Given all of the above I think we'd want to display `achievementCredential.name` if it exists, otherwise `achievementSubject.achievement.name`, otherwise `vc.name`, or suppress the display of the line entirely unless there is a `achievement.image.id` (or the previous data elements we were using for the image in this location) even if any of the name fields are empty. We might consider strongly encouraging one of the name fields to be non-empty.

The info we want displayed for the BCSI test is _**"Certified Evaluator"**_ and comes from [Column H of the Google sheet](https://docs.google.com/spreadsheets/d/1hZ9z9jTFToAN4Lgvpm1r8B8S_6beU4Bsft-6cA3HvzM/edit#gid=0).

**4. What LCW is displaying on the Home Screen.**
If I'm reading the JSON right, `credentialSubject.achievement.name` is showing up on the Home Screen as in the screenshot. The text "Documentation and SOP seems to come from `credentialSubject.achievement.name`. (It's the only entry that "Documentation and SOP" shows up.)

As above perhaps there's additional logic of what gets displayed there from previous contexts we've supported and need to continue to support in addition to supporting the name as per above.

**5. Note that the same display of data is happening in the credentials that Kayode created as test samples.**

The same mismatch between the Home Screen and Credential preview screen happens for the [credentials Kayode created](https://github.com/digitalcredentials/docs/tree/add-example-credentials/example-credentials).


**By observation (and not looking at the source code), it seems we need to both issue the correct information as the credential is issued, and know how we're displaying what's getting issued.**

**Comment by kayaelle** [comment] 2023-08-14 15:01
Thanks, @bmuramatsu - I've updated: `https://github.com/digitalcredentials/ops/issues/10` to update both AchievementCredential.name and achievement.name to "Certified Evaluator". This issue also references an edit for the criteria.narrative.

I did a review of the spreadsheet & the badge data. If you would like to take another pass at it, please do that soon. 

Once @dmitrizagidulin has updated the badge template, I'll work with Atomic Jolt team on the display issue.

**Comment by kayaelle** [comment] 2023-08-14 19:43
Atomic Jolt -  please use AchievementCredential.name wherever the name of the credential mentioned.

**Comment by jmcioffi4** [comment] 2023-08-14 21:39
PR: https://github.com/digitalcredentials/learner-credential-wallet/pull/484

**Comment by kayaelle** [comment] 2023-09-06 19:33
Confirmed that displays are using AchievementCredential.name in iOS and android

**Closed by kayaelle** 2023-09-06 19:33 UTC
